// Copyright 2026 Nekzus Solutions and contributors
// SPDX-License-Identifier: Apache-2.0

import crypto from "node:crypto";

export enum ProofType {
	HMAC_LEGACY = 0x00,
	GROTH16 = 0x02,
}

export const RECEIPT_VERSION_V1 = 0x01;
export const RECEIPT_VERSION_V2 = 0x02;
export const ZK_JOURNAL_V2_SIZE = 144;

export interface ZkJournalV2 {
	/** Image ID (SHA-256) of the guest interpreter */
	guestImageId: Buffer;
	/** SHA-256 digest of injected logic */
	logicDigest: Buffer;
	/** SHA-256 digest of dataset records */
	datasetDigest: Buffer;
	/** SHA-256 digest of sanitized output */
	outputDigest: Buffer;
	/** Micro-instruction fuel consumed */
	fuelConsumed: bigint;
	/** Timestamp in milliseconds since unix epoch */
	executionTimestamp: bigint;
}

export type ZkPolicy = "none" | "optimistic" | "required";

export interface ZkReceipt {
	/** Cryptographic proof generated by a zero-knowledge VM (e.g., RISC Zero, SP1) or Groth16 */
	proof: Buffer;
	/** The public inputs/outputs of the execution (the "Journal" in RISC Zero terminology) */
	journal: Buffer;
	/** The expected image ID / verification key of the WASM binary that was executed */
	imageId: Buffer;
	/** Type of cryptographic proof (HMAC legacy or Groth16) */
	proofType?: ProofType;
	/** Binary receipt version (0x01 or 0x02) */
	version?: number;
}

export class ZkVerificationError extends Error {
	constructor(message: string) {
		super(`ZK Verification Failed: ${message}`);
		this.name = "ZkVerificationError";
	}
}

/**
 * Serializes a structured ZkJournalV2 into a strictly validated 144-byte binary layout.
 */
export function encodeJournalV2(fields: ZkJournalV2): Buffer {
	if (fields.guestImageId.length !== 32) {
		throw new ZkVerificationError(
			`Invalid guestImageId size: expected 32 bytes, got ${fields.guestImageId.length}`,
		);
	}
	if (fields.logicDigest.length !== 32) {
		throw new ZkVerificationError(
			`Invalid logicDigest size: expected 32 bytes, got ${fields.logicDigest.length}`,
		);
	}
	if (fields.datasetDigest.length !== 32) {
		throw new ZkVerificationError(
			`Invalid datasetDigest size: expected 32 bytes, got ${fields.datasetDigest.length}`,
		);
	}
	if (fields.outputDigest.length !== 32) {
		throw new ZkVerificationError(
			`Invalid outputDigest size: expected 32 bytes, got ${fields.outputDigest.length}`,
		);
	}

	const buf = Buffer.alloc(ZK_JOURNAL_V2_SIZE);
	fields.guestImageId.copy(buf, 0);
	fields.logicDigest.copy(buf, 32);
	fields.datasetDigest.copy(buf, 64);
	fields.outputDigest.copy(buf, 96);
	buf.writeBigUInt64BE(BigInt(fields.fuelConsumed), 128);
	buf.writeBigUInt64BE(BigInt(fields.executionTimestamp), 136);

	return buf;
}

/**
 * Deserializes and validates a 144-byte binary buffer into a typed ZkJournalV2.
 */
export function decodeJournalV2(buf: Buffer): ZkJournalV2 {
	if (buf.length !== ZK_JOURNAL_V2_SIZE) {
		throw new ZkVerificationError(
			`Invalid ZkJournalV2 size: expected ${ZK_JOURNAL_V2_SIZE} bytes, got ${buf.length}`,
		);
	}

	return {
		guestImageId: Buffer.from(buf.subarray(0, 32)),
		logicDigest: Buffer.from(buf.subarray(32, 64)),
		datasetDigest: Buffer.from(buf.subarray(64, 96)),
		outputDigest: Buffer.from(buf.subarray(96, 128)),
		fuelConsumed: buf.readBigUInt64BE(128),
		executionTimestamp: buf.readBigUInt64BE(136),
	};
}

export interface DecodedReceipt {
	version: number;
	proofType: ProofType;
	journal: Buffer;
	proof: Buffer;
	raw: Buffer;
}

export const receiptCodec = {
	/**
	 * Encodes a version 2 Binary Receipt with trailing SHA-256 checksum.
	 * Layout: [0x02][proofType: 1B][journalLen: 4B UInt32BE][journal][proof][checksum: 32B]
	 */
	encodeV2(proofType: ProofType, journal: Buffer, proof: Buffer): Buffer {
		const header = Buffer.alloc(6);
		header.writeUInt8(RECEIPT_VERSION_V2, 0);
		header.writeUInt8(proofType, 1);
		header.writeUInt32BE(journal.length, 2);

		const payload = Buffer.concat([header, journal, proof]);
		const checksum = crypto.createHash("sha256").update(payload).digest();

		return Buffer.concat([payload, checksum]);
	},

	/**
	 * Decodes any LIOP Binary Receipt (v1 HMAC or v2 ZK).
	 */
	decode(raw: Buffer): DecodedReceipt {
		if (!raw || raw.length === 0) {
			throw new ZkVerificationError(
				"Empty or malformed zero-knowledge proof array.",
			);
		}

		const version = raw[0];

		if (version === RECEIPT_VERSION_V1) {
			if (raw.length < 35) {
				throw new ZkVerificationError(
					"Malformed receipt: invalid header or length.",
				);
			}
			const journalLen = raw.readUInt16BE(1);
			if (raw.length < 3 + journalLen + 32) {
				throw new ZkVerificationError(
					"Malformed receipt: truncated journal or seal.",
				);
			}
			const journal = Buffer.from(raw.subarray(3, 3 + journalLen));
			const seal = Buffer.from(
				raw.subarray(3 + journalLen, 3 + journalLen + 32),
			);

			return {
				version: RECEIPT_VERSION_V1,
				proofType: ProofType.HMAC_LEGACY,
				journal,
				proof: seal,
				raw,
			};
		}

		if (version === RECEIPT_VERSION_V2) {
			// Minimum size: 1 (version) + 1 (proofType) + 4 (journalLen) + 0 (journal) + 0 (proof) + 32 (checksum) = 38
			if (raw.length < 38) {
				throw new ZkVerificationError(
					"Malformed receipt v2: buffer too short (< 38 bytes).",
				);
			}

			const proofType = raw[1] as ProofType;
			const journalLen = raw.readUInt32BE(2);

			if (raw.length < 6 + journalLen + 32) {
				throw new ZkVerificationError(
					"Malformed receipt v2: truncated payload.",
				);
			}

			const payload = raw.subarray(0, raw.length - 32);
			const expectedChecksum = raw.subarray(raw.length - 32);
			const actualChecksum = crypto
				.createHash("sha256")
				.update(payload)
				.digest();

			if (!crypto.timingSafeEqual(expectedChecksum, actualChecksum)) {
				throw new ZkVerificationError("Receipt checksum verification failed.");
			}

			const journal = Buffer.from(raw.subarray(6, 6 + journalLen));
			const proof = Buffer.from(raw.subarray(6 + journalLen, raw.length - 32));

			return {
				version: RECEIPT_VERSION_V2,
				proofType,
				journal,
				proof,
				raw,
			};
		}

		throw new ZkVerificationError(
			`Unsupported receipt version: 0x${version.toString(16)}`,
		);
	},
};

/**
 * ZK-Proofs Verifier for Logic-Injection-on-Origin Protocol (LIOP)
 *
 * Validates that an executed Logic (WASM) actually produced the reported output,
 * verifying the Zero-Knowledge receipt generated by the remote host's Trusted Execution
 * Environment (TEE) or zkVM (Zero-Knowledge Virtual Machine).
 */
export const ZkVerifier = {
	/**
	 * Validates a ZK receipt using structural Binary Receipt verification.
	 * Parses the HMAC-SHA256 commitment format (v1) and verifies journal integrity.
	 *
	 * @param receipt - Complete ZkReceipt to verify
	 * @param expectedImageId - Hash or ImageID of the WASM file dispatched to the host
	 * @throws ZkVerificationError if the proof is invalid or image IDs mismatch
	 * @returns true if the proof mathematically verifies the execution
	 */
	verify(
		receipt: ZkReceipt,
		expectedImageId: Buffer,
		sessionSecret?: Buffer,
	): boolean {
		// 1. Verify Image ID (Ensures the host executed the exact logic we sent, not a malicious one)
		if (!receipt.imageId.equals(expectedImageId)) {
			throw new ZkVerificationError(
				"ImageID mismatch. The remote origin executed a different WASM payload.",
			);
		}

		// 2. Validate Proof Structure
		if (receipt.proof.length === 0) {
			throw new ZkVerificationError(
				"Empty or malformed zero-knowledge proof array.",
			);
		}

		// 3. Cryptographic Validation (Binary Receipt)
		const proofBuf = Buffer.from(receipt.proof);
		if (proofBuf.length < 35 || proofBuf[0] !== 0x01) {
			throw new ZkVerificationError(
				"Malformed receipt: invalid header or length.",
			);
		}
		const journalLen = proofBuf.readUInt16BE(1);
		const journal = proofBuf.subarray(3, 3 + journalLen);
		const seal = proofBuf.subarray(3 + journalLen);

		if (seal.length !== 32) {
			throw new ZkVerificationError(
				"Invalid seal: expected 32-byte HMAC-SHA256.",
			);
		}

		// Verify journal contains matching imageId
		try {
			const journalData = JSON.parse(journal.toString());
			if (journalData.image_id !== receipt.imageId.toString("hex")) {
				throw new ZkVerificationError(
					"Journal imageId does not match receipt header.",
				);
			}
		} catch (_e) {
			throw new ZkVerificationError("Failed to parse journal data.");
		}

		// 4. Mathematical Verification (HMAC-SHA256)
		if (sessionSecret && sessionSecret.length > 0) {
			const expectedSeal = crypto
				.createHmac("sha256", sessionSecret)
				.update(journal)
				.digest();
			if (!crypto.timingSafeEqual(seal, expectedSeal)) {
				throw new ZkVerificationError(
					"Invalid seal: HMAC verification failed.",
				);
			}
		}

		return true;
	},

	/**
	 * Derives a predictable ImageID (usually a Hash) from a raw WASM binary.
	 *
	 * @param wasmBytes - The raw bytes of the WASM logic file
	 * @returns The SHA-256 ImageID of the logic
	 */
	deriveImageId(wasmBytes: Buffer): Buffer {
		return crypto.createHash("sha256").update(wasmBytes).digest();
	},
};
